on:
  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - run: emsdk/emsdk --help
      - run: emsdk/emsdk install latest
      - run: emsdk/emsdk activate latest
      - run: source emsdk/emsdk_env.sh
      - uses: actions/checkout@v4
      - run: emcmake cmake -S . -B build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
